module.exports = {
  BranchstaffassignmentCreatedTopic:
    "librarymanagementsystem-adminops-service-branchstaffassignment-created",
  BranchstaffassignmentUpdatedTopic:
    "librarymanagementsystem-adminops-service-branchstaffassignment-updated",
  BranchstaffassignmentDeletedTopic:
    "librarymanagementsystem-adminops-service-branchstaffassignment-deleted",
  IssueescalationCreatedTopic:
    "librarymanagementsystem-adminops-service-issueescalation-created",
  IssueescalationUpdatedTopic:
    "librarymanagementsystem-adminops-service-issueescalation-updated",
  IssueescalationDeletedTopic:
    "librarymanagementsystem-adminops-service-issueescalation-deleted",
  MongoadminconfigCreatedTopic:
    "librarymanagementsystem-adminops-service-mongoadminconfig-created",
  MongoadminconfigUpdatedTopic:
    "librarymanagementsystem-adminops-service-mongoadminconfig-updated",
  MongoadminconfigDeletedTopic:
    "librarymanagementsystem-adminops-service-mongoadminconfig-deleted",
  ExternalnotificationconfigCreatedTopic:
    "librarymanagementsystem-adminops-service-externalnotificationconfig-created",
  ExternalnotificationconfigUpdatedTopic:
    "librarymanagementsystem-adminops-service-externalnotificationconfig-updated",
  ExternalnotificationconfigDeletedTopic:
    "librarymanagementsystem-adminops-service-externalnotificationconfig-deleted",
  SystembackupauditCreatedTopic:
    "librarymanagementsystem-adminops-service-systembackupaudit-created",
  SystembackupauditUpdatedTopic:
    "librarymanagementsystem-adminops-service-systembackupaudit-updated",
  SystembackupauditDeletedTopic:
    "librarymanagementsystem-adminops-service-systembackupaudit-deleted",
  BranchpurchaseorderCreatedTopic:
    "librarymanagementsystem-adminops-service-branchpurchaseorder-created",
  BranchpurchaseorderUpdatedTopic:
    "librarymanagementsystem-adminops-service-branchpurchaseorder-updated",
  BranchpurchaseorderDeletedTopic:
    "librarymanagementsystem-adminops-service-branchpurchaseorder-deleted",
};
